In [ ]:
import numpy as np
import matplotlib.pyplot as plt



First neural network:
containing 3 neurons each with a value [1.2,5.1,2.1], weight[3.1,2.1.8.7] and bias 3
so the output of these neurons will be input of output layer.

In [ ]:
inputs=[1.2, 5.1, 2.1]
weights=[3.1,2.1,8.7]
bias=3

output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

35.7


In [ ]:
inputs=[1, 2, 3]
weights=[0.2, 0.8, -0.5]
bias=2

output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

2.3


In [ ]:
inputs=[1, 2, 3, 2.5]
weights=[0.2, 0.8, -0.5, 1.0]
bias=2

output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias
print(output)

4.8


In [ ]:
inputs=[1, 2, 3, 2.5]
weights1=[0.2, 0.8, -0.5, 1.0]
weights2=[0.5, -0.91, 0.26, -0.5]
weights3=[-0.26, -0.27, 0.17, 0.87]
bias1=2
bias2=3
bias3=0.5

output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
print(output)

[4.8, 1.21, 2.385]


In [ ]:
inputs=[1, 2, 3, 2.5]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases=[2,3,0.5]

layer_outputs=[]
for neuron_weights, neuron_bias in zip(weights, biases):
  print(neuron_weights," ", neuron_bias," 1st")
  neuron_output=0
  for n_input, weight in zip(inputs, neuron_weights):
    print(n_input," ",weight," 2nd")
    neuron_output+=n_input*weight
  neuron_output+=neuron_bias
  layer_outputs.append(neuron_output)

print(layer_outputs)







[0.2, 0.8, -0.5, 1.0]   2  1st
1   0.2  2nd
2   0.8  2nd
3   -0.5  2nd
2.5   1.0  2nd
[0.5, -0.91, 0.26, -0.5]   3  1st
1   0.5  2nd
2   -0.91  2nd
3   0.26  2nd
2.5   -0.5  2nd
[-0.26, -0.27, 0.17, 0.87]   0.5  1st
1   -0.26  2nd
2   -0.27  2nd
3   0.17  2nd
2.5   0.87  2nd
[4.8, 1.21, 2.385]


In [ ]:
import numpy as np
inputs=[1, 2, 3, 2.5]

weights=[0.2, 0.8, -0.5, 1.0]

bias=2

output=np.dot(inputs,weights)+bias
print(output)



4.8


In [ ]:
import numpy as np
inputs=[[1, 2, 3, 2.5],
        [2.0,5.0,1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

weights=[[0.2, 0.8, -0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases=[2,3,0.5]

layer1_output=np.dot(inputs,np.array(weights)).T)+biases
print(layer1_output)

weights2=[[0.1,-0.14,0.5],
         [-0.5,0.12,-0.33],
         [-0.44, 0.73, -0.13]]

biases2=[-1,2,-0.5]

layer2_output=np.dot(layer1_output,np.array(weights2).T)+biases2
print(layer1_output)


[[ 4.8    1.21   2.385]
 [ 7.9   -1.29   0.54 ]
 [ 1.41   1.051  0.026]]
[[ 4.8    1.21   2.385]
 [ 7.9   -1.29   0.54 ]
 [ 1.41   1.051  0.026]]
