In [ ]:
import numpy as np
import math



#Neural Network Basics

In [ ]:
inputs = [1.2, 5.1, 2.1]
weights = [3.1, 2.1, 8.7]
bias = 3.0

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

35.7


#Mathematical calculations

In [ ]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2.0
bias2 = 3.0
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
print(output)

[4.8, 1.21, 2.385]


#By numpy

In [ ]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

output = np.dot(weights, inputs) + biases
print(output)

[4.8   1.21  2.385]


#Defining 2 layer NN

In [ ]:
np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


#Softmax calculations

In [ ]:
softmax_output = [0.7, 0.1, 0.2]
target_output = [1, 0, 0]

loss = -(math.log(softmax_output[0]) * target_output[0] +
         math.log(softmax_output[1]) * target_output[1] +
         math.log(softmax_output[2]) * target_output[2])

print(loss)

print(-math.log(0.7))
print(-math.log(0.5))


0.35667494393873245
0.35667494393873245
0.6931471805599453


#Neural Network---- 300 dim vector, output 1 value

In [ ]:
np.random.seed(0)

x = np.random.randn(5, 300)
print(x)


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def softmax(self, x):
        return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)

    def sig(self, x):
        return 1/(1 + np.exp(-x))

    def forward(self, inputs):
        self.output = self.sig(np.dot(inputs, self.weights) + self.biases)


layer1 = Layer_Dense(300,128)
layer2 = Layer_Dense(128,64)
layer3 = Layer_Dense(64,1)

layer1.forward(x)
layer2.forward(layer1.output)
layer3.forward(layer2.output)

print(np.sum(layer3.output))

[[ 1.76405235  0.40015721  0.97873798 ...  0.58295368 -0.39944903
   0.37005589]
 [-1.30652685  1.65813068 -0.11816405 ... -0.21673147 -0.9301565
  -0.17858909]
 [-1.55042935  0.41731882 -0.94436849 ... -1.5415874   2.59442459
  -0.40403229]
 [-1.46173269 -0.68343977  0.3675449  ... -0.59377745 -2.01188032
   0.58970361]
 [-0.89636972 -1.96273201  1.58482053 ... -0.24679356 -1.07934317
  -0.11422555]]
1.8540740851287625


=====================================

#NN Produces a column vector

In [ ]:
class NN:
    def __init__(self):
        self.input_size = 300
        self.hidden_size1 = 128
        self.hidden_size2 = 64
        self.output_size = 1
        self.weights1 = np.random.randn(self.input_size, self.hidden_size1)
        self.weights2 = np.random.randn(self.hidden_size1, self.hidden_size2)
        self.weights3 = np.random.randn(self.hidden_size2, self.output_size)

    def sig(self,x):
        return 1/(1 + np.exp(-x))

    def forward(self, x):
        h1 = self.sig(np.dot(x, self.weights1))
        h2 = self.sig(np.dot(h1, self.weights2))
        output = np.dot(h2, self.weights3)
        return output

    def softmax(self, x):
        return np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)


nn = NN()
x = np.random.randn(5, 300)
output = nn.forward(x)
print(output)

[[ 2.87631142]
 [-2.68543646]
 [-1.76685814]
 [-6.79381638]
 [-2.60843937]]


#Taking sum of column vector to get one numerical value

In [ ]:
class NN2:
    def __init__(self):
        self.input_dim = 300
        self.hidden_dim1 = 128
        self.hidden_dim2 = 64
        self.output_dim = 1
        self.W1 = np.random.randn(self.hidden_dim1, self.input_dim)
        self.b1 = np.random.randn(self.hidden_dim1)
        self.W2 = np.random.randn(self.hidden_dim2, self.hidden_dim1)
        self.b2 = np.random.randn(self.hidden_dim2)
        self.W3 = np.random.randn(self.output_dim, self.hidden_dim2)
        self.b3 = np.random.randn(self.output_dim)

    def sig(self,x):
        return 1/(1 + np.exp(-x))

    def forward(self, X):
        L1 = self.sig(np.dot(self.W1, X.T) + self.b1.reshape(-1, 1))
        L2 = self.sig(np.dot(self.W2, L1) + self.b2.reshape(-1, 1))
        L3 = self.sig(np.dot(self.W3, L2) + self.b3.reshape(-1, 1))
        output = np.sum(L3)
        return output


nn2 = NN2()
x = np.random.randn(5, 300)
print(x)
output = nn2.forward(x)
print(output)

[[-0.68850505 -0.55654582 -1.99202607 ...  0.51513974 -0.00986603
   0.46955072]
 [-1.95513697  0.17081812 -1.20061398 ...  1.51421791 -1.10782602
   0.37952939]
 [ 1.7709085   0.49840167 -0.24363041 ...  0.89501937 -0.24989759
   0.02544529]
 [ 0.76790934  0.39772379 -1.28605947 ... -0.002438    1.16372727
  -1.94810007]
 [ 1.46031038  1.55500125 -1.22550287 ...  0.5406267  -0.11519955
   0.88387229]]
1.3076315991828378


=========================

#Input vectors are w2v representations

In [ ]:
import gensim.downloader as api
w2v_model = api.load("word2vec-google-news-300")

[=================================================-] 99.9% 1661.5/1662.8MB downloaded


In [ ]:
class NN3:
    def __init__(self):
        self.input_dim = 300
        self.hidden_dim1 = 128
        self.hidden_dim2 = 64
        self.output_dim = 1
        self.W1 = np.random.randn(self.hidden_dim1, self.input_dim)
        self.b1 = np.random.randn(self.hidden_dim1)
        self.W2 = np.random.randn(self.hidden_dim2, self.hidden_dim1)
        self.b2 = np.random.randn(self.hidden_dim2)
        self.W3 = np.random.randn(self.output_dim, self.hidden_dim2)
        self.b3 = np.random.randn(self.output_dim)

    def sig(self,x):
        return 1/(1 + np.exp(-x))

    def forward(self, X):
        L1 = self.sig(np.dot(self.W1, X.T) + self.b1.reshape(-1, 1))
        L2 = self.sig(np.dot(self.W2, L1) + self.b2.reshape(-1, 1))
        L3 = self.sig(np.dot(self.W3, L2) + self.b3.reshape(-1, 1))
        output = self.sig(np.sum(L3))
        return output





In [ ]:
nn3 = NN3()
sentence = "I am a cat"
tokens = sentence.split()
vectors = []
for token in tokens:
    vec = w2v_model[token] if token in w2v_model else np.zeros(300)
    vectors.append(vec)


vectors = np.array(vectors)
print(vectors)

output = nn3.forward(vectors)
print(output)

[[ 0.07910156 -0.0050354   0.11181641 ... -0.0067749   0.04272461
  -0.10351562]
 [-0.16699219 -0.06640625  0.05737305 ... -0.05419922  0.1171875
   0.08398438]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.0123291   0.20410156 -0.28515625 ...  0.4921875  -0.27539062
   0.05615234]]
0.9806846636253227


#NN in Pytorch

In [ ]:
import pandas as pd
import torch
import torch.nn as nn
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


# Text preprocessing module

In [ ]:
class TextPreprocessor:
    def __init__(self):
        self.stop_words = set(stopwords.words('english'))
        self.punctuations = set(string.punctuation)

    def process_text(self, text):
        text = text.lower()
        text = re.sub(r'http\S+', '', text)
        text = re.sub(r'<.*?>', '', text)
        text = ''.join(char for char in text if char not in self.punctuations)
        tokens = word_tokenize(text)
        tokens = [token for token in tokens if token not in self.stop_words]
        text = ' '.join(tokens)

        return text

    def process_column(self, df, column_name):
        df[column_name] = df[column_name].apply(self.process_text)

        return df

#Loading dataset

In [ ]:
data = pd.read_csv('restuarents.csv', encoding='ISO-8859-1')
print(data.head())

                                                text  label
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1


#Applying preprocessor

In [ ]:
preprocessor = TextPreprocessor()
df = preprocessor.process_column(data, 'text')

print(df.head())

                                                text  label
0                                    wow loved place      1
1                                         crust good      0
2                                tasty texture nasty      0
3  stopped late may bank holiday rick steve recom...      1
4                        selection menu great prices      1


#w2v function

In [ ]:
def w2v(sentence):
    tokens = sentence.split()
    vec = []
    for token in tokens:
        if token in w2v_model:
            vec.append(w2v_model[token])
        else:
            vec.append(np.zeros(300))

    #vec = sum(vec)/len(vec)
    return torch.tensor(vec)

In [ ]:
t = w2v("I am a student")
t.shape

torch.Size([4, 300])

#Dataset's child class for preparing data + Tensor conversion

In [ ]:
class Datasethelper(Dataset):
  def __init__(self, df):
    super().__init__()
    self.data = df['text'].values
    self.labels = df['label'].values

  def __len__(self):
    return len(self.data)

  def __getitem__(self, index):
    text = self.data[index]
    label = self.labels[index]
    w2v_data = w2v(text)
    label = torch.tensor( label , dtype=torch.float32)
    print(w2v_data.shape)
    return w2v_data, label


#Splitting dataset + dataloader

In [ ]:
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

train_helper = Datasethelper(train_df)
test_helper = Datasethelper(test_df)


train_dloader = DataLoader(train_helper, batch_size = 10 , shuffle = True)
test_dloader = DataLoader(test_helper, batch_size = 10 , shuffle = False)



In [ ]:
for batch,label in train_dloader:
  break
print(batch.shape)
print(label.shape)

torch.Size([3, 300])
torch.Size([3, 300])
torch.Size([2, 300])
torch.Size([7, 300])
torch.Size([10, 300])
torch.Size([4, 300])
torch.Size([2, 300])
torch.Size([6, 300])
torch.Size([8, 300])
torch.Size([7, 300])


RuntimeError: ignored

In [ ]:
class NN4(nn.Module):
    def __init__(self, input_dim = 300, hidden_dim1 = 128, hidden_dim2 = 64):
        super().__init__()
        self.input_dim = input_dim
        self.hidden_dim1 = hidden_dim1
        self.hidden_dim2 = hidden_dim2
        self.output_dim = 1
        self.LL1 = nn.Linear(self.input_dim, self.hidden_dim1)
        self.LL2 = nn.Linear(self.hidden_dim1, self.hidden_dim2)
        self.FL = nn.Linear(self.hidden_dim2, self.output_dim)
        self.sigmoid = nn.Sigmoid()

    def forward(self, X):
        X = X.mean(axis=1)
        X = self.LL1(X)
        X = self.sigmoid(X)
        X = self.LL2(X)
        X = self.sigmoid(X)
        X = self.FL(X)

        return X


In [ ]:
NNmodel = NN4()
crit = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(NNmodel.parameters(), lr = 0.001)

In [ ]:
#def accuracy(y_pred, y_acc):
    #y_pred = y_pred.argmax(dim=1)
    #correct = (y_pred == y_acc).sum().item()
    #total = y_acc.size(0)
    #return correct / total

In [ ]:
for epoch in range(10):
  for x, y in train_dloader:
    predicted_y = NNmodel(x)
    loss = crit(predicted_y, y)
    loss.backward()
    optimizer.zero_grad()
    optimizer.step()

    accuracy = accuracy(predicted_y.detach().numpy, y.detach().numpy)
    print(accuracy)

RuntimeError: ignored